"""
openfoam_adjoint.py — drag-adjoint surface sensitivity for the half-car CFD
case, using ESI's `adjointOptimisationFoam`.

This is the piece that makes the OpenFOAM case actually "work with the 3
parts": Part 3's `pipeline_interface.real_bindings.run_adjoint` is a hard
`? UNRESOLVED NotImplementedError` stub (see part3-simulation/pipeline_interface.py),
and Part 1's `phi_updater.apply_adjoint_sensitivity_symmetric` (aka `update_phi`)
requires a `right_half_sensitivity` array with exactly one scalar per vertex of
the right-half trimesh, in the SAME order as `mesh.vertices`. This module
produces that array.

Turbulence pairing: kOmegaSST (primal) / adjointkOmegaSST (adjoint) — matching
the Part 2 spec's own stated turbulence model ("laminar baseline, k-omega SST
for final validation"), so the sensitivity field is computed with the SAME
closure used to validate D20/L/Cm, rather than mixing in an unrelated model.

An earlier version of this module used Spalart-Allmaras, on the mistaken
assumption (from having found only ONE tutorial) that it was the only
primal/adjoint turbulence pairing ESI ships. That was wrong: inspecting the
compiled libadjointOptimisation.so's symbol table shows `adjointkOmegaSST` is
a complete, independently-registered adjointRASModel implementation (same
factory table as adjointSpalartAllmaras) with its own tutorials
(shapeOptimisation/naca0012/kOmegaSST/lift and
shapeOptimisation/sbend/turbulent/kOmegaSST/opt, openfoam2412). Both were
used as the ground truth for the boundary conditions and dict schema below —
not assumed from documentation.

Design:
  * `optimisationManager singleRun` — ONE invocation of adjointOptimisationFoam
    runs the primal solve (SIMPLE, kOmegaSST, nIters primal_iters) and then the
    adjoint solve (adjointSimple, adjointkOmegaSST, nIters adjoint_iters)
    internally, driven entirely by optimisationDict. No separate solver
    binaries to call.
  * The primal U/p/k/omega/nut fields are generated by
    openfoam_case._write_initial_fields (same domain, same patches, same
    wall-function conventions already live-verified for the forward-only
    case) — not duplicated here.
  * The objective is `type force, direction (1,0,0)` (raw drag), weight 1 —
    i.e. the CFD side computes unweighted dD20/dSurface. The project's
    Objective = w_D20 x D20 x ADJOINT_HALF_CAR_SCALING (Part 2's
    adjoint_contract.py) is linear in this, so the business-logic weight and
    the 0.5 half-car scaling are applied in Python afterward, not baked into
    the OpenFOAM dict.
  * `sensitivityType surfacePoints` on the `car` patch gives a sensitivity
    value AT MESH POINTS directly (not per-face) — the right shape for a
    per-vertex array — but those points are snappyHexMesh's own (snapped)
    surface points, not the original STL's vertices. This module
    nearest-neighbour-maps snappy's sensitivity points back onto the ORIGINAL
    STL's vertex coordinates (via scipy.spatial.cKDTree) so the returned
    array lines up 1:1, in order, with `trimesh.load(stl_path).vertices` —
    exactly what Part 1 expects to zip against its own mesh.
"""

from __future__ import annotations

import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Sequence

import numpy as np

import openfoam_case as oc


@dataclass(frozen=True)
class AdjointRunConfig:
    """Config for the drag-adjoint sensitivity solve.

    Turbulence is always kOmegaSST (primal) / adjointkOmegaSST (adjoint) —
    matching Part 2's forward validation model (see module docstring). There
    is no turbulence_model choice here, unlike OpenFOAMRunConfig.
    """

    reference_speed_mps: float = 20.0
    air_density_kgm3: float = 1.225
    kinematic_viscosity_m2s: float = oc._MU_AIR_PA_S / 1.225
    primal_iters: int = 1000
    adjoint_iters: int = 1000
    resolution: str = "medium"
    # ⚠ Keep at 1. The MPI branch of run_adjoint_stages runs, but the
    # sensitivity readback does not survive it: read_polymesh_points() reads
    # constant/polyMesh/points, which under -parallel is still the SERIAL
    # BACKGROUND blockMesh (snappy writes processor*/constant/polyMesh), so
    # parse_sensitivity_points raises "N values but M points". invoke_adjoint
    # enforces this rather than letting it fail hours in. The forward solve
    # (openfoam_case) has no such coupling and can use MPI freely.
    n_subdomains: int = 1
    underbody_refinement_level: int = 1
    stage_timeout_s: int = 14400
    keep_run_dir: bool = False
    # Nearest-neighbour matches beyond this distance (m) from any original STL
    # vertex are treated as unmapped and raise, rather than silently pairing
    # a sensitivity value with the wrong point.
    max_point_match_distance_m: float = 5e-3
    # Fraction of STL vertices allowed to have NO adjoint sensitivity point
    # within max_point_match_distance_m. Those are frozen (zero sensitivity)
    # rather than fatal -- see map_sensitivity_to_stl_vertices. Above this, the
    # CFD mesh is too coarse to represent the body and we stop rather than
    # optimise a surface that is mostly held still.
    # 0.30, not 0.05. The measured share on this geometry at `medium` is 21.36%,
    # essentially all of it STL over-resolution plus enclosed voids (median
    # distance 0.652 mm). At 0.05 the PRODUCTION path could never complete an
    # adjoint: --smoke overrode it to 0.25 and so passed, while a real run --
    # which passes adjoint_kwargs={} -- would have failed every candidate. The
    # guard that actually detects a bad mesh is max_median_match_distance_m.
    max_unmapped_fraction: float = 0.30
    # Median STL-vertex-to-adjoint-point distance above which the CFD mesh is
    # judged not to represent the body at all. 3 mm against a measured healthy
    # median of 0.652 mm -- loose enough not to fire on a coarser-but-usable
    # mesh, tight enough that a mesh which has genuinely drifted or collapsed
    # cannot pass.
    max_median_match_distance_m: float = 3e-3
    # Divergence trap for the adjoint solve, as a multiple of the freestream.
    # See check_adjoint_magnitude: the residual check cannot detect steady
    # exponential growth, and a diverged adjoint yields a sensitivity field that
    # unit-RMS normalisation turns into silence rather than into an error.
    #
    # Set from measurement. Healthy solves observed on this case: |Ua| max
    # 6.96 (ATCModel cancel), 28.1 (nSmooth 10), 78.2 (nSmooth 3), all with
    # p50 well under 1 m/s. A diverging one reached max 2.82e+03 at 1000
    # iterations and 7.2e+45 unsmoothed. The first version of this field used
    # 1.0e4, chosen before any healthy solve had been measured, and it let the
    # 2.82e+03 case through. 100x freestream = 2000 m/s is still ~25x above the
    # worst healthy maximum seen, so it stays a runaway trap rather than an
    # accuracy check, but it no longer sits above the failures it exists for.
    max_adjoint_velocity_ratio: float = 100.0

    def __post_init__(self):
        if self.resolution not in oc.RESOLUTION_REFINEMENT:
            raise ValueError(
                f"resolution must be one of {sorted(oc.RESOLUTION_REFINEMENT)}, "
                f"got {self.resolution!r}"
            )
        if self.reference_speed_mps <= 0:
            raise ValueError("reference_speed_mps must be > 0")
        if self.primal_iters <= 0 or self.adjoint_iters <= 0:
            raise ValueError("primal_iters and adjoint_iters must be > 0")
        if self.n_subdomains != 1:
            raise ValueError(
                "AdjointRunConfig.n_subdomains must be 1: the surfacePoints "
                "sensitivity readback reads constant/polyMesh/points, which "
                "under -parallel is the background blockMesh, not the snapped "
                "mesh the sensitivity field is defined on. Fix "
                "read_polymesh_points (reconstructParMesh) before enabling MPI "
                "here. The FORWARD solve is unaffected and may use MPI."
            )

    def as_forward_config(self) -> oc.OpenFOAMRunConfig:
        """Adapts this config to openfoam_case.OpenFOAMRunConfig so the
        primal U/p/k/omega/nut fields and turbulenceProperties can be
        generated by the same, already-verified functions the forward-only
        case uses — same domain, same patches, same wall functions."""
        return oc.OpenFOAMRunConfig(
            reference_speed_mps=self.reference_speed_mps,
            air_density_kgm3=self.air_density_kgm3,
            kinematic_viscosity_m2s=self.kinematic_viscosity_m2s,
            turbulence_model="kOmegaSST",
            resolution=self.resolution,
            n_subdomains=self.n_subdomains,
        )


# ---------------------------------------------------------------------------
# Dictionary builders (pure, unit-tested)
# ---------------------------------------------------------------------------

def build_adjoint_ras_properties() -> str:
    """Verified against tutorials/incompressible/adjointOptimisationFoam/
    shapeOptimisation/naca0012/kOmegaSST/lift/constant/adjointRASProperties —
    unlike the SA pairing, kOmegaSST needs no extra coeffs sub-dict here."""
    # object name must match the FILENAME the dict is written to
    # (constant/adjointRASProperties), or a strict IOdictionary read can reject
    # it. It said "adjointTurbulenceProperties" before.
    #
    # FROZEN TURBULENCE. Changed 2026-07-27 from adjointkOmegaSST, which
    # crashed with SIGFPE at adjoint iteration 277 of 500:
    #
    #     #6  gaussLaplacianScheme<Vector,double>::fvmLaplacian(...)
    #     #9  adjointkOmegaSST::divDevReff(...)
    #     #13 adjointSolverManager::solveAdjointEquations()
    #
    # Everything up to that point was healthy -- the primal converged, pa went
    # 0.506 -> 0.003, Ua ~1e-4, ka/wa small and well behaved. The failure is
    # specifically inside the adjoint turbulence model's effective-viscosity
    # term on this geometry.
    #
    # Two facts decided the replacement, both read off the installed release
    # rather than assumed: adjointLaminar is used by 14 shipped tutorials
    # against adjointkOmegaSST's 2, and NO tutorial uses `adjointTurbulence
    # off`, so freezing via that switch is not the idiom -- adjointLaminar is.
    # (adjointSpalartAllmaras has 36, but the adjoint turbulence model must
    # match the primal, and our primal is kOmegaSST.)
    #
    # What frozen turbulence costs: it assumes d(nu_t)/d(shape) = 0, so the
    # sensitivity ignores how the turbulent viscosity field responds to moving
    # the surface. It is standard industrial practice and normally preserves
    # the sensitivity DIRECTION while biasing its magnitude.
    #
    # For THIS pipeline the cost is close to nil: phi_updater.combine_gradients
    # normalises the aero field to unit RMS before weighting, so the magnitude
    # is discarded anyway and only the spatial pattern and sign survive. We are
    # trading away a quantity the level-set update does not use.
    #
    # The PRIMAL stays kOmegaSST -- it converges and produces the drag VALUE.
    # Only the adjoint's turbulence treatment is frozen.
    return oc._header("dictionary", "adjointRASProperties") + """
adjointRASModel adjointLaminar;

adjointTurbulence on;
"""


def build_adjoint_control_dict(cfg: AdjointRunConfig) -> str:
    end_time = cfg.primal_iters + cfg.adjoint_iters
    # writeFormat MUST stay ascii here (unlike the forward case, which is now
    # binary): _parse_foam_scalar_list reads the pointSensNormal* field as text.
    # writeInterval == endTime writes once, at the end -- only the final
    # sensitivity field is read. NOT `writeControl onEnd`: that value belongs to
    # the function-object enum, not Time::writeControls, and v2412 aborts on it.
    return oc._header("dictionary", "controlDict") + f"""
application     adjointOptimisationFoam;
startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         {end_time};
deltaT          1;
writeControl    timeStep;
writeInterval   {end_time};
purgeWrite      0;
writeFormat     ascii;
writePrecision  8;
writeCompression off;
timeFormat      general;
timePrecision   6;
runTimeModifiable true;
"""


# Sensitivity type written into optimisationDict.
#
# VERIFIED against the shipped v2412 tutorials on a real install (2026-07-26),
# not inferred. `grep sensitivityType` across
# tutorials/incompressible/adjointOptimisationFoam gives:
#     topO 31, shapeFI 20, surfacePoints 9, shapeESI 10, surface 4, multiple 6
# and sensitivityMaps/motorBike -- the external-aero case closest to ours --
# uses `sensitivityType surfacePoints` for its per-POINT map, which is the one
# Part 1's per-vertex contract needs.
#
# An intermediate version of this file guessed `ESI` from an observed output
# filename and moved the block from `designVariables` to `sensitivities`. Both
# were wrong: v2412 has no `sensitivities` block, and `shapeESI` is a different
# (surface-integral) formulation. The preflight caught it before any solve ran.
SENSITIVITY_TYPE = "surfacePoints"


def build_optimisation_dict(cfg: AdjointRunConfig, ref_area_half: float) -> str:
    """`singleRun` manager: one primal solve (kOmegaSST) then one adjoint
    solve (adjointkOmegaSST), objective = raw drag force (weight 1 — see
    module docstring for why the business weight is applied in Python, not
    here). residualControl includes k/omega (primal) and ka/wa (adjoint) —
    verified against sbend/turbulent/kOmegaSST/opt, which is the only shipped
    example with the k/omega transport equations actually solved.

    ⚠ SCHEMA — the one thing in this file that cannot be verified without a
    live OpenFOAM. Targeting ESI **v2412**. Two things changed here in the
    2026-07-24 audit, both of which would have made every adjoint solve fail:

      1. `computeSensitivities true;` was MISSING from the adjoint solver.
         Without it the solver runs to completion and writes no sensitivity
         field at all — find_sensitivity_file would then raise FileNotFoundError
         after a multi-hour solve.
      2. The sensitivity request was `optimisation { designVariables {
         sensitivityType surfacePoints; ... } }`. `designVariables` requires a
         `type` entry (v2112+), which was absent, and `surfacePoints` is the
         pre-v2112 type name. For a singleRun sensitivity map the block is
         `optimisation { sensitivities { type ESI; ... } }`.

    Run `preflight_adjoint_schema()` on the VM before the first solve — it
    diffs this against the installed release's own shipped tutorial and is the
    5-minute way to settle any residual doubt.
    """
    aref = max(ref_area_half, 1e-9)
    u = cfg.reference_speed_mps
    rho = cfg.air_density_kgm3
    return oc._header("dictionary", "optimisationDict") + f"""
optimisationManager singleRun;

primalSolvers
{{
    op1
    {{
        active                 true;
        type                   incompressible;
        solver                 simple;

        solutionControls
        {{
            consistent yes;
            nIters {cfg.primal_iters};
            residualControl
            {{
                "p.*"       1.e-5;
                "U.*"       1.e-5;
                "k.*"       1.e-5;
                "omega.*"   1.e-5;
            }}
        }}
    }}
}}

adjointManagers
{{
    adjManager1
    {{
        primalSolver             op1;
        adjointSolvers
        {{
            adjS1
            {{
                active                 true;
                type                   incompressible;
                solver                 adjointSimple;
                computeSensitivities   true;

                objectives
                {{
                    type incompressible;
                    objectiveNames
                    {{
                        drag
                        {{
                            weight     1.;
                            type       force;
                            patches    (car);
                            direction  (1 0 0);
                            Aref       {aref};
                            rhoInf     {rho};
                            UInf       {u};
                        }}
                    }}
                }}

                // ADJOINT TRANSPOSE CONVECTION. nSmooth is the single setting
                // that decides whether this solver produces a gradient or
                // garbage, so it is set from measurement, not from a tutorial.
                //
                // Copying sensitivityMaps/motorBike gave nSmooth 0, and the
                // adjoint DIVERGED: |Ua| reached p50 6.2e+38 / max 7.2e+45
                // while every residualControl reported convergence, because a
                // field growing at a constant factor per iteration holds its
                // RELATIVE residual constant (Uax sat at exactly 0.00036110203
                // for hundreds of iterations). The 1e50 sensitivity that came
                // out had 99.97% of its sum of squares in ten mesh points, so
                // unit-RMS normalisation downstream turned it into silence
                // rather than an error.
                //
                // Measured on this case, 150 adjoint iterations each:
                //   nSmooth  0   |Ua| max 4.33e+13   sens top10 99.97%  (diverges)
                //   nSmooth  1   |Ua| max 8.91e+04   sens top10 99.96%  (diverges)
                //   nSmooth  3   |Ua| max 7.82e+01   sens top10 24.00%  (converges)
                //   nSmooth 10   |Ua| max 2.81e+01   sens top10 20.30%  (converges)
                //   ATCModel cancel  |Ua| max 6.96   sens top10 20.38%  (converges)
                //
                // nSmooth 10 matches `cancel` on sensitivity quality without
                // deleting the ATC term, so the gradient stays CONSISTENT --
                // smoothing the term is a far milder approximation than
                // dropping it. |Ua| max 28 m/s against a 20 m/s freestream is
                // physically sane.
                //
                // A bluff body with a large separated wake is the classic ATC
                // instability, and this car is a brick with a 1.5 mm ride-height
                // gap spanned by ~2.7 cells. If a future geometry diverges again,
                // check_adjoint_magnitude will raise rather than let it through;
                // the ladder above is the thing to re-run, and `cancel` is the
                // fallback if smoothing stops being enough.
                ATCModel
                {{
                    ATCModel          standard;
                    extraConvection   0;
                    nSmooth           10;
                    zeroATCPatchTypes (wall patch);
                    maskType          pointCells;
                }}

                solutionControls
                {{
                    consistent yes;
                    nIters {cfg.adjoint_iters};
                    residualControl
                    {{
                        "pa.*"       1.e-5;
                        "Ua.*"       1.e-5;
                        "ka.*"       1.e-5;
                        "wa.*"       1.e-5;
                    }}
                }}
            }}
        }}
    }}
}}

optimisation
{{
    designVariables
    {{
        // Layout copied from the shipped v2412 sensitivityMaps/motorBike
        // tutorial (its `pointBased` sub-dict), reduced to the single
        // sensitivity type we need. That tutorial requests several types at
        // once via `sensitivityType multiple; sensitivityTypes (...)`; asking
        // for exactly one is the same schema without the list.
        //
        // `surfacePoints` gives one scalar per MESH POINT, which is what Part
        // 1's per-vertex contract needs after map_sensitivity_to_stl_vertices.
        // The face-based alternatives (`surface`, `shapeESI`, `shapeFI`) are
        // per-face and would not line up.
        sensitivityType    {SENSITIVITY_TYPE};
        patches            (car);
        // includeMeshMovement DEFAULTS TO TRUE (v2412
        // sensitivityShapeESI.C:110). Leaving it on adds the adjoint
        // mesh-movement field `ma` to the sensitivity chain, and on this
        // external-aero case that field blows up: measured `Max ma 8.57e+46`
        // from its FIRST iteration, giving a surface sensitivity spanning
        // -1.13e+57..4.74e+55 in which the TOP TEN POINTS carried 99.33% of
        // the sum of squares.
        //
        // That silently killed the aero term. combine_gradients normalises
        // each gradient to unit RMS, so ten spikes absorbing 99.33% of the
        // norm rescale the real signal to ~0.7% of it; the p99.9 clip in
        // apply_adjoint_to_unified then trims the spikes as well. Measured
        // consequence: flipping the sign of the whole aero gradient changed
        // the resulting geometry by 0.369 mm^3 out of a 932 mm^3 step —
        // 0.04%. The optimiser was running on the mass gradient alone.
        //
        // Every shipped v2412 shapeOptimisation tutorial (sbend, naca0012
        // drag + moment) sets this false; only the naca0012 sensitivity-MAP
        // demo leaves it true. The adjoint FLOW solve is healthy either way
        // (Ua/pa residuals converged, no bounding) — it is only this
        // auxiliary chain that is bad.
        includeMeshMovement false;
        adjointEikonalSolver
        {{
            tolerance 1.e-5;
            iters     1000;
            epsilon   0.1;
        }}
    }}
}}
"""


def preflight_adjoint_schema(bashrc: Optional[str] = None) -> dict:
    """Compare our optimisationDict against the installed release's own shipped
    adjoint tutorials. Run this ONCE on the VM before the first real solve.

    Everything else in this pipeline can be checked without OpenFOAM; the
    optimisationDict schema cannot, and it is version-dependent (the
    designVariables/sensitivities split changed at v2112). Rather than trust a
    docstring, read the ground truth off the machine that will run it.

    Returns a dict with the tutorial dicts found and the entries we care about,
    and prints a human-readable report. Never raises for a missing tutorial —
    a missing tutorial tree is a reason to check by hand, not a crash.
    """
    import os as _os
    import subprocess as _sp

    resolved = oc.find_openfoam_bashrc(bashrc)
    if resolved is None:
        raise oc.OpenFOAMNotFoundError(
            "preflight needs a real ESI OpenFOAM environment to read "
            "$FOAM_TUTORIALS from."
        )
    proc = _sp.run(["bash", "-lc", f"source '{resolved}' && echo $FOAM_TUTORIALS"],
                   stdout=_sp.PIPE, stderr=_sp.STDOUT, text=True, timeout=120)
    tutorials = proc.stdout.strip().splitlines()[-1].strip() if proc.stdout.strip() else ""
    report: dict = {"tutorials_root": tutorials, "found": [], "ours": {
        "block": "sensitivities", "type": SENSITIVITY_TYPE,
        "computeSensitivities": True,
    }}
    if not tutorials or not _os.path.isdir(tutorials):
        print(f"[preflight] $FOAM_TUTORIALS not usable ({tutorials!r}); check by hand.")
        return report

    root = Path(tutorials) / "incompressible" / "adjointOptimisationFoam"
    for dict_path in sorted(root.rglob("system/optimisationDict")):
        text = dict_path.read_text(encoding="utf-8", errors="replace")
        entry = {
            "path": str(dict_path),
            "has_sensitivities_block": bool(re.search(r"^\s*sensitivities\s*$", text, re.M)),
            "has_designVariables_block": bool(re.search(r"^\s*designVariables\s*$", text, re.M)),
            "computeSensitivities": bool(re.search(r"computeSensitivities\s+true", text)),
            "type_entries": sorted(set(re.findall(r"^\s*(?:sensitivityType|type)\s+(\w+)\s*;", text, re.M))),
        }
        report["found"].append(entry)

    print(f"[preflight] {len(report['found'])} shipped optimisationDict(s) under {root}")
    for e in report["found"]:
        print(f"  {e['path']}")
        print(f"    sensitivities-block={e['has_sensitivities_block']} "
              f"designVariables-block={e['has_designVariables_block']} "
              f"computeSensitivities={e['computeSensitivities']}")
        print(f"    type entries: {e['type_entries']}")
    print(f"[preflight] ours: sensitivities-block, type {SENSITIVITY_TYPE}, "
          f"computeSensitivities true")
    print("[preflight] If the shipped dicts disagree, edit build_optimisation_dict "
          "and SENSITIVITY_TYPE to match THEM — they are the ground truth for "
          "this install.")
    return report


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _write_adjoint_fields(zero_dir: Path) -> None:
    """Ua/pa/ka/wa for MY 7-patch domain (inlet, outlet, symmetry, outer,
    upperWall, lowerWall, car). BC types verified against the shipped
    kOmegaSST adjoint tutorials:
      - wall types (kaqRWallFunction, waWallFunction, adjointWallVelocity):
        naca0012/kOmegaSST/lift and sbend/turbulent/kOmegaSST/opt.
      - inlet/outlet types for a domain with SEPARATE inlet and outlet
        patches (my domain, unlike naca0012's single combined freestream
        patch): sbend/turbulent/kOmegaSST/opt, the only shipped kOmegaSST
        example with distinct Inlet/Outlet patches.
      - pa's outlet type here is adjointFarFieldPressure (not sbend's
        adjointOutletPressure): my domain is an open external-aero far-field
        boundary (matches the topology of the SA motorBike case, which used
        adjointFarFieldPressure), not an enclosed duct exit like sbend.
      - outer/upperWall (slip, non-wall, non-farfield) have no confirmed
        reference for ka/wa; `slip` is used there for consistency with how
        Ua/p/k/omega already treat those patches as generic slip boundaries
        in this project's own (already-verified) forward case.
    """
    _write(zero_dir / "Ua", oc._header("volVectorField", "Ua") + """
dimensions      [0 1 -1 0 0 0 0];
internalField   uniform (0 0 0);
boundaryField
{
    inlet       { type adjointInletVelocity; value uniform (0 0 0); }
    outlet      { type adjointOutletVelocity; value uniform (0 0 0); }
    symmetry    { type symmetryPlane; }
    outer       { type slip; }
    upperWall   { type slip; }
    lowerWall   { type adjointWallVelocity; value uniform (0 0 0); }
    car         { type adjointWallVelocity; value uniform (0 0 0); }
}
""")
    _write(zero_dir / "pa", oc._header("volScalarField", "pa") + """
dimensions      [0 2 -2 0 0 0 0];
internalField   uniform 0;
boundaryField
{
    inlet       { type zeroGradient; }
    outlet      { type adjointFarFieldPressure; value uniform 0; }
    symmetry    { type symmetryPlane; }
    outer       { type zeroGradient; }
    upperWall   { type zeroGradient; }
    lowerWall   { type zeroGradient; }
    car         { type zeroGradient; }
}
""")
    _write(zero_dir / "ka", oc._header("volScalarField", "ka") + """
dimensions      [0 0 0 0 0 0 0];
internalField   uniform 0;
boundaryField
{
    inlet       { type adjointZeroInlet; value uniform 0; }
    outlet      { type adjointOutletKa; value uniform 0; }
    symmetry    { type symmetryPlane; }
    outer       { type slip; }
    upperWall   { type slip; }
    lowerWall   { type kaqRWallFunction; value uniform 0; }
    car         { type kaqRWallFunction; value uniform 0; }
}
""")
    _write(zero_dir / "wa", oc._header("volScalarField", "wa") + """
dimensions      [0 2 -1 0 0 0 0];
internalField   uniform 0;
boundaryField
{
    inlet       { type adjointZeroInlet; value uniform 0; }
    outlet      { type adjointOutletWa; value uniform 0; }
    symmetry    { type symmetryPlane; }
    outer       { type slip; }
    upperWall   { type slip; }
    lowerWall   { type waWallFunction; value uniform 0; }
    car         { type waWallFunction; value uniform 0; }
}
""")


# ---------------------------------------------------------------------------
# Case assembly + orchestration
# ---------------------------------------------------------------------------

def build_adjoint_case(run_dir: str, stl_path: str, cfg: AdjointRunConfig) -> dict:
    """Generate a complete adjoint case under run_dir. Reuses the geometry
    (bounds, domain box, blockMesh/snappy/surfaceFeatureExtract/meshQuality
    dict builders, and the primal U/p/k/omega/nut/turbulenceProperties
    writers) from openfoam_case.py — only adjointRASProperties, the adjoint
    0/ fields, optimisationDict, and controlDict's application differ from
    the forward-only case."""
    run = Path(run_dir)
    if run.exists():
        shutil.rmtree(run)
    (run / "system").mkdir(parents=True, exist_ok=True)
    (run / "constant" / "triSurface").mkdir(parents=True, exist_ok=True)
    (run / "0").mkdir(parents=True, exist_ok=True)

    forward_cfg = cfg.as_forward_config()

    bounds = oc.stl_bounds(stl_path)
    (x0, y0, z0), (x1, y1, z1) = bounds
    ref_len = max(x1 - x0, 1e-4)
    frontal_area_half = oc.compute_frontal_area_half(stl_path)
    box_min, box_max = oc.domain_box(bounds)
    loc = oc.location_in_mesh(bounds)
    cell_size = max(ref_len / 12.0, 1e-4)

    oc._normalise_solid_name(stl_path, run / "constant" / "triSurface" / "car.stl")

    refinement = oc.RESOLUTION_REFINEMENT[cfg.resolution]

    _write(run / "system" / "blockMeshDict", oc.build_blockmesh_dict(box_min, box_max, cell_size))
    _write(run / "system" / "snappyHexMeshDict",
           oc.build_snappy_dict("car.stl", loc, refinement, add_layers=True,
                                underbody=oc.underbody_box(bounds),
                                underbody_extra_levels=cfg.underbody_refinement_level))
    _write(run / "system" / "controlDict", build_adjoint_control_dict(cfg))
    _write(run / "system" / "fvSchemes", _FV_SCHEMES_ADJOINT)
    _write(run / "system" / "fvSolution", _FV_SOLUTION_ADJOINT)
    _write(run / "system" / "surfaceFeatureExtractDict",
           oc._header("dictionary", "surfaceFeatureExtractDict") + oc._SURFACE_FEATURE_EXTRACT_BODY)
    _write(run / "system" / "meshQualityDict", oc._MESH_QUALITY_DICT)
    _write(run / "system" / "decomposeParDict", oc._decompose_dict(cfg.n_subdomains))
    _write(run / "system" / "optimisationDict", build_optimisation_dict(cfg, frontal_area_half))
    _write(run / "constant" / "transportProperties", oc.build_transport_properties(forward_cfg))
    _write(run / "constant" / "turbulenceProperties", oc.build_turbulence_properties(forward_cfg))
    _write(run / "constant" / "adjointRASProperties", build_adjoint_ras_properties())

    # Primal fields (U, p, k, omega, nut) -- same domain/patches/wall
    # functions as the already-verified forward-only case.
    oc._write_initial_fields(run / "0", forward_cfg, ref_len)
    # Adjoint fields (Ua, pa, ka, wa).
    _write_adjoint_fields(run / "0")

    return {
        "bounds": bounds,
        "frontal_area_half": frontal_area_half,
        "cell_size_m": cell_size,
        "domain_box": (box_min, box_max),
        "location_in_mesh": loc,
    }


def run_adjoint_stages(run_dir: str, cfg: AdjointRunConfig, bashrc: str,
                       timeout_s: Optional[int] = None) -> dict:
    """surfaceFeatureExtract -> blockMesh -> snappyHexMesh -> checkMesh ->
    adjointOptimisationFoam (single invocation runs primal then adjoint,
    per optimisationDict's singleRun manager)."""
    timeout_s = cfg.stage_timeout_s if timeout_s is None else timeout_s
    run = Path(run_dir)
    oc._run("surfaceFeatureExtract", run, bashrc, "surfaceFeatureExtract.log", timeout_s)
    oc._run("blockMesh", run, bashrc, "blockMesh.log", timeout_s)
    if cfg.n_subdomains > 1:
        # Same ordering fix as openfoam_case.run_stages: mesh SERIALLY, then
        # decompose the finished mesh. Decomposing first splits the 0/ fields
        # against the blockMesh, which has no `car` patch yet, and the solve
        # then dies with "Cannot find patchField entry for car".
        # (n_subdomains is currently pinned to 1 for the adjoint anyway -- see
        # AdjointRunConfig -- so this branch is future-proofing, not live.)
        oc._run("snappyHexMesh -overwrite", run, bashrc, "snappyHexMesh.log", timeout_s)
        checkmesh = oc._run("checkMesh", run, bashrc, "checkMesh.log", timeout_s)
        oc._run("decomposePar -force", run, bashrc, "decomposePar.log", timeout_s)
        solver_log = oc._run(f"mpirun -np {cfg.n_subdomains} adjointOptimisationFoam -parallel",
                             run, bashrc, "adjoint.log", timeout_s)
        oc._run("reconstructPar -latestTime", run, bashrc, "reconstructPar.log", timeout_s)
    else:
        oc._run("snappyHexMesh -overwrite", run, bashrc, "snappyHexMesh.log", timeout_s)
        checkmesh = oc._run("checkMesh", run, bashrc, "checkMesh.log", timeout_s)
        solver_log = oc._run("adjointOptimisationFoam", run, bashrc, "adjoint.log", timeout_s)
    return {"checkmesh_log": checkmesh, "solver_log": solver_log}


# ---------------------------------------------------------------------------
# Sensitivity output discovery + parsing (pure, unit-tested against fixtures)
# ---------------------------------------------------------------------------

def find_sensitivity_file(run_dir: str) -> Path:
    """Locate the surfacePoints sensitivity output.

    Verified against a live run (openfoam2412): the file is named
    `pointSensNormal<adjointSolverName><suffix>` (here `pointSensNormaladjS1ESI`,
    from optimisationDict's adjoint solver name `adjS1`) and is written as a
    plain `pointScalarField` covering EVERY point of the volume mesh (not a
    curated list of just the design-patch points) — most values are 0, with
    nonzero values at points on/near the sensitivity patch. This is a
    different shape than the naive assumption of a small "list of (point,
    value) pairs on the patch" file; that assumption was wrong and this was
    only discovered by actually running the solver and inspecting its output
    directory, not from documentation.

    We search for `pointSensNormal*` broadly rather than hardcoding the exact
    solver-name suffix, and take the newest match (highest write time), so a
    different adjoint solver name in optimisationDict still resolves.
    """
    root = Path(run_dir)
    candidates = [p for p in root.rglob("pointSensNormal*") if p.is_file()]
    if not candidates:
        raise FileNotFoundError(
            f"No pointSensNormal* sensitivity output found under {run_dir}. "
            "Expected a pointScalarField file written by the surfacePoints "
            "sensitivity type, named pointSensNormal<adjointSolverName><suffix>."
        )
    return max(candidates, key=lambda p: p.stat().st_mtime)


def _parse_foam_scalar_list(text: str) -> np.ndarray:
    """Parse the `internalField nonuniform List<scalar> N ( v1 v2 ... vN )`
    block of an OpenFOAM pointScalarField/volScalarField ASCII file.

    Scans for a bare integer count line immediately followed by a `(` line
    (the "N\\n(\\n...\\n)" list convention OpenFOAM uses everywhere), rather
    than a single regex over the whole file, so a boundaryField sub-dict
    elsewhere in the same file can't confuse the match.
    """
    lines = text.splitlines()
    start = None
    count = None
    for i, line in enumerate(lines):
        s = line.strip()
        if s.isdigit() and i + 1 < len(lines) and lines[i + 1].strip() == "(":
            start = i + 2
            count = int(s)
            break
    if start is None or count is None:
        raise ValueError("Could not find a 'N\\n(\\n...values...\\n)' list in the field file")
    values = []
    for line in lines[start:]:
        s = line.strip()
        if s == ")":
            break
        if not s:
            continue
        try:
            values.append(float(s))
        except ValueError:
            continue
    if len(values) != count:
        raise ValueError(f"Expected {count} scalar values, parsed {len(values)}")
    return np.array(values, dtype=np.float64)


def _parse_foam_vector_list(text: str) -> np.ndarray:
    """Parse a `N\\n(\\n(x y z)\\n...\\n)` OpenFOAM vectorField/pointField
    (used for constant/polyMesh/points)."""
    lines = text.splitlines()
    start = None
    count = None
    for i, line in enumerate(lines):
        s = line.strip()
        if s.isdigit() and i + 1 < len(lines) and lines[i + 1].strip() == "(":
            start = i + 2
            count = int(s)
            break
    if start is None or count is None:
        raise ValueError("Could not find a 'N\\n(\\n(x y z)...\\n)' list in the points file")
    rows = []
    for line in lines[start:]:
        s = line.strip()
        if s == ")":
            break
        if not s:
            continue
        m = re.match(r"\(\s*([0-9.eE+-]+)\s+([0-9.eE+-]+)\s+([0-9.eE+-]+)\s*\)", s)
        if m:
            rows.append([float(m.group(1)), float(m.group(2)), float(m.group(3))])
    if len(rows) != count:
        raise ValueError(f"Expected {count} points, parsed {len(rows)}")
    return np.array(rows, dtype=np.float64)


def read_polymesh_points(run_dir: str) -> np.ndarray:
    """Read constant/polyMesh/points -> array of shape (N, 3), index-aligned
    with the sensitivity pointScalarField's internalField (both are per
    mesh-point, same N, same order — this is how OpenFOAM point fields work:
    they're defined directly over the mesh's point list)."""
    path = Path(run_dir) / "constant" / "polyMesh" / "points"
    if not path.is_file():
        raise FileNotFoundError(f"constant/polyMesh/points not found under {run_dir}")
    return _parse_foam_vector_list(path.read_text(encoding="utf-8", errors="replace"))


def parse_sensitivity_points(sensitivity_text: str, points: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Pair the sensitivity pointScalarField's values with mesh point
    coordinates (both index-aligned by mesh point ID). Returns (points[N,3],
    values[N]) covering every mesh point -- including the many zero-valued
    interior points, which is fine: map_sensitivity_to_stl_vertices's nearest-
    neighbour search will naturally prefer the nearby nonzero surface points
    over distant interior ones, and the max-distance guard catches anything
    that goes wrong."""
    values = _parse_foam_scalar_list(sensitivity_text)
    if len(values) != len(points):
        raise ValueError(
            f"Sensitivity field has {len(values)} values but the mesh has "
            f"{len(points)} points -- they must be the same mesh."
        )
    return points, values


def map_sensitivity_to_stl_vertices(
    stl_path: str,
    sens_points: np.ndarray,
    sens_values: np.ndarray,
    max_distance_m: float,
    max_unmapped_fraction: float = 0.30,
    max_median_match_distance_m: float = 3e-3,
) -> np.ndarray:
    """Nearest-neighbour-map CFD-mesh sensitivity points onto the ORIGINAL
    STL's vertex order, so the result lines up 1:1 with
    `trimesh.load(stl_path).vertices` — the shape Part 1's
    apply_adjoint_sensitivity_symmetric (right_half_sensitivity) requires.

    snappyHexMesh snaps surface points to the geometry within a small
    tolerance, so CFD points are close to but not identical to STL vertices;
    nearest-neighbour is the correct correspondence here, not an exact match.
    Raises if any STL vertex has no CFD sensitivity point within
    max_distance_m — silently assigning a distant, wrong value would corrupt
    the phi update rather than fail loudly.
    """
    from scipy.spatial import cKDTree

    stl_verts = np.array(oc.read_ascii_stl_vertices(stl_path), dtype=np.float64)
    tree = cKDTree(sens_points)
    dist, idx = tree.query(stl_verts, k=1)
    bad = dist > max_distance_m
    n_bad = int(np.sum(bad))
    frac = n_bad / max(len(stl_verts), 1)

    # Some orphans are EXPECTED and zeroing them is the honest answer. The STL
    # carries interior geometry the CFD mesh does not resolve -- the O18.25 mm
    # cartridge bore, the 3.175 mm halo pocket recess, the ballast slot -- and a
    # vertex with no nearby CFD point simply has no computed sensitivity. Zero
    # means "no information, do not move this point", which is safe; inventing a
    # value from a distant point would corrupt the phi update, which is what the
    # original hard failure was protecting against.
    #
    # Measured on the first real adjoint solve (2026-07-26): at `coarse`
    # resolution the car patch had only 9,885 points against 360,000 STL
    # vertices, and 77,355 (21.5%) were orphaned -- so hard-failing meant NO
    # iteration could ever complete. The fraction is the real signal: a few
    # percent is unresolved recesses, a large fraction means the mesh does not
    # cover the body at all (or units/geometry drifted), which still raises.
    # THE MEDIAN is what detects "the CFD mesh does not cover the body". The
    # unmapped FRACTION does not, because it conflates three different things:
    #
    #   (a) STL over-resolution -- 360,000 STL vertices against a far sparser
    #       CFD surface, so a minority of vertices land in sparse patches. Benign.
    #   (b) enclosed voids (halo cavity, cartridge bore) that snappyHexMesh
    #       legitimately deletes. Freezing those is physically correct: no flow,
    #       no drag sensitivity.
    #   (c) the CFD mesh genuinely failing to represent the body. The real risk.
    #
    # Measured 2026-07-26/27 at `medium`: median distance 0.652 mm, unmapped at
    # 5 mm 21.36%, unmapped at 20 mm 3.84%. The bulk is resolved to well under a
    # millimetre while a fifth of vertices trip a 5 mm test -- so the fraction
    # was reporting (a) and (b), and the 5% default made the PRODUCTION path
    # unpassable on a geometry the smoke path handled only because it set 0.25.
    # A median that blows up is (c) and nothing else.
    med = float(np.median(dist))
    if med > max_median_match_distance_m:
        raise ValueError(
            f"median STL-vertex-to-adjoint-point distance is {med*1000:.2f} mm "
            f"(limit {max_median_match_distance_m*1000:.2f} mm). The CFD mesh "
            f"does not represent this geometry -- the whole surface is poorly "
            f"matched, not just recesses and enclosed voids. Raise `resolution`, "
            f"or check that the STL and the meshed case have not drifted apart."
        )
    if frac > max_unmapped_fraction:
        raise ValueError(
            f"{n_bad}/{len(stl_verts)} STL vertices ({frac*100:.1f}%) have no "
            f"adjoint sensitivity point within {max_distance_m} m, above the "
            f"{max_unmapped_fraction*100:.0f}% limit (median distance "
            f"{med*1000:.2f} mm). With a healthy median this is usually STL "
            "over-resolution plus enclosed voids rather than a bad mesh; raise "
            "AdjointRunConfig.max_unmapped_fraction if you accept that share of "
            "the surface being frozen, or raise `resolution` to shrink it."
        )
    out = sens_values[idx].astype(np.float64, copy=True)
    if n_bad:
        out[bad] = 0.0
        print(f"[openfoam_adjoint] {n_bad}/{len(stl_verts)} vertices "
              f"({frac*100:.2f}%) had no sensitivity within "
              f"{max_distance_m*1000:.1f} mm -- frozen (zero sensitivity)")
    return out


# ---------------------------------------------------------------------------
# Top-level entry point
# ---------------------------------------------------------------------------

def _parse_foam_vector_magnitudes(text: str) -> Optional[np.ndarray]:
    """|v| per cell from an OpenFOAM ASCII volVectorField, or None if uniform."""
    m = re.search(
        r"internalField\s+nonuniform\s+List<vector>\s*\n?\s*(\d+)\s*\n\((.*?)\n\)\s*;",
        text, re.S,
    )
    if not m:
        return None
    rows = [ln.strip() for ln in m.group(2).splitlines() if ln.strip().startswith("(")]
    if not rows:
        return None
    vals = np.array([[float(x) for x in r.strip("() ").split()] for r in rows])
    return np.linalg.norm(vals, axis=1)


def check_adjoint_magnitude(run_dir: str, cfg: "AdjointRunConfig") -> None:
    """Fail a DIVERGED adjoint solve that the residual check calls converged.

    THE FAILURE THIS EXISTS FOR (measured 2026-07-27). The adjoint velocity
    settled at |Ua| p50 = 6.2e+38, max 7.2e+45, and the run was reported
    converged the whole way: `Solving for Uax, Initial residual = 0.00036110203`
    repeated identically for hundreds of iterations. A CONSTANT relative
    residual does not mean a converged solution -- it means the field is
    growing by a constant factor each iteration, so |r|/|b| never changes.
    ~1.09x per iteration reaches 1e38 over 1000 iterations while every
    residualControl in the case reports success.

    Downstream this produced sensitivities of order 1e50 in which the top ten
    mesh points carried 99.97% of the sum of squares. Because combine_gradients
    normalises to unit RMS, that silently zeroed the aero term and the optimiser
    ran on the mass gradient alone for every iteration ever executed.

    Ua has dimensions of velocity, so the freestream sets the scale: an adjoint
    velocity thousands of times the freestream is not a converged adjoint. The
    bound is deliberately loose (default 1e4 x U_inf) -- this is a divergence
    trap, not an accuracy check, and it must not fire on a merely ill-conditioned
    but usable solve.
    """
    root = Path(run_dir)
    candidates = [p for p in root.glob("*/Ua") if p.is_file()]
    if not candidates:
        return  # nothing written; find_sensitivity_file reports the real error
    mags = None
    for p in sorted(candidates, key=lambda q: q.stat().st_mtime, reverse=True):
        mags = _parse_foam_vector_magnitudes(p.read_text(errors="replace"))
        if mags is not None:
            break
    if mags is None:
        return  # only uniform (unsolved) Ua present

    limit = cfg.max_adjoint_velocity_ratio * cfg.reference_speed_mps
    peak = float(mags.max())
    if not np.isfinite(peak) or peak > limit:
        raise RuntimeError(
            f"adjoint solve DIVERGED: max|Ua| = {peak:.4e} m/s against a "
            f"{cfg.reference_speed_mps} m/s freestream (limit "
            f"{limit:.4e} = {cfg.max_adjoint_velocity_ratio}x). Residual "
            f"convergence does not rule this out: a constant relative residual "
            f"is the signature of steady exponential growth. The sensitivity "
            f"from this solve is not a gradient. Check the ATCModel setting — "
            f"adjoint transpose convection is the usual cause around a bluff "
            f"body with a large separated wake. Run dir kept: {run_dir}"
        )


def invoke_adjoint(
    stl_path: str,
    case_dir: str,
    cfg: Optional[AdjointRunConfig] = None,
    bashrc: Optional[str] = None,
    search_roots: Optional[Sequence[str]] = None,
) -> np.ndarray:
    """Full adjoint pipeline: build case, run primal+adjoint, parse
    sensitivity, map onto the original STL's vertex order.

    Returns the RAW (unweighted, weight=1 drag-direction) per-vertex
    dD20_half/dSurface sensitivity array. Applying the project's objective
    weight (w_D20) and ADJOINT_HALF_CAR_SCALING is the caller's job
    (cfd_wrapper.run_half_car_adjoint) — see module docstring for why.

    search_roots: passed through to oc.find_openfoam_bashrc -- pass [] to
    force "not found" deterministically in tests regardless of what's
    actually installed on the host (see find_openfoam_bashrc's docstring;
    an invalid bashrc= alone is NOT sufficient, since discovery falls back
    to real install roots on any machine that has ESI OpenFOAM)."""
    import os

    cfg = cfg or AdjointRunConfig()
    resolved_bashrc = oc.find_openfoam_bashrc(bashrc, search_roots=search_roots)
    if resolved_bashrc is None:
        raise oc.OpenFOAMNotFoundError(
            "No ESI OpenFOAM environment found for the adjoint solve. Set "
            "$WM_PROJECT_DIR or $FOAM_BASHRC, or pass bashrc=... ."
        )
    import uuid as _uuid

    # uuid4, not hash(stl_path) % 10_000 — Part 3 runs candidates as threads in
    # one process, so a hash collision would rmtree a live sibling case.
    run_dir = str(Path(case_dir) / "adjoint_runs" / f"run_{os.getpid()}_{_uuid.uuid4().hex[:12]}")
    build_adjoint_case(run_dir, stl_path, cfg)
    succeeded = False
    try:
        run_adjoint_stages(run_dir, cfg, resolved_bashrc)
        check_adjoint_magnitude(run_dir, cfg)
        sens_file = find_sensitivity_file(run_dir)
        mesh_points = read_polymesh_points(run_dir)
        sens_points, sens_values = parse_sensitivity_points(
            sens_file.read_text(encoding="utf-8", errors="replace"), mesh_points
        )
        out = map_sensitivity_to_stl_vertices(
            stl_path, sens_points, sens_values,
            cfg.max_point_match_distance_m,
            # Was omitted, so this silently fell back to the 5% default while
            # AdjointRunConfig.max_unmapped_fraction was set to 0.25 and looked
            # honoured. A sed patch had updated the dataclass field and the
            # function signature but not this call; verifying "the field exists"
            # and "the parameter exists" proved nothing about the wiring.
            cfg.max_unmapped_fraction,
            cfg.max_median_match_distance_m,
        )
        succeeded = True
        return out
    finally:
        # Keep the run dir on FAILURE, always — see openfoam_case.invoke.
        if succeeded and not cfg.keep_run_dir:
            shutil.rmtree(run_dir, ignore_errors=True)
        elif not succeeded:
            print(f"[openfoam_adjoint] stage failed — run dir KEPT for diagnosis: {run_dir}")


_FV_SCHEMES_ADJOINT = oc._header("dictionary", "fvSchemes") + """
ddtSchemes
{
    default         steadyState;
}

gradSchemes
{
    default         Gauss linear;
}

divSchemes
{
    default            Gauss linear;

    // TURBULENCE TRANSPORT IS UPWIND, NOT linearUpwind. Changed 2026-07-27
    // after adjointOptimisationFoam died with SIGFPE on the first medium-
    // resolution run:
    //
    //     bounding omega, min: -3.1e+119  max: 2.6e+135
    //     #3 Foam::multiply(...)  in libOpenFOAM.so
    //     #4 ... libincompressibleTurbulenceModels.so
    //     #7 Foam::simple::mainIter()  in libadjointOptimisation.so
    //    #10 Foam::optimisationManager::solvePrimalEquations()
    //
    // It never reached the adjoint at all -- omega blew up in the PRIMAL solve
    // at step 77 of 500. linearUpwind undershoots to negative omega near walls;
    // `bounding` clips it, but the SST blending functions multiply k/omega and
    // that product is where the FPE lands.
    //
    // The decisive evidence is that the FORWARD case solves the same kOmegaSST
    // model on the same geometry and converges (T_raw = 3.19 s) -- and it uses
    // `bounded Gauss upwind` for k and omega. Matching it here is the smallest
    // change consistent with something that demonstrably works on this
    // geometry. Momentum keeps linearUpwind: U was never the problem.
    //
    // The shipped tutorials do use linearUpwind for these, but they are tuned
    // cases (motorBike, sbend). A rectangular billet with sharp edges is a much
    // harsher test than either.
    div(phi,U)         bounded Gauss linearUpwind gradUConv;
    div(phi,k)         bounded Gauss upwind;
    div(phi,omega)     bounded Gauss upwind;
    div(-phi,Ua)       bounded Gauss linearUpwind gradUaConv;
    div(-phi,ka)       bounded Gauss upwind;
    div(-phi,wa)       bounded Gauss upwind;
}

laplacianSchemes
{
    default         Gauss linear limited 0.333;
}

interpolationSchemes
{
    default         linear;
}

snGradSchemes
{
    default         limited 0.333;
}

wallDist
{
    method meshWave;
}
"""

_FV_SOLUTION_ADJOINT = oc._header("dictionary", "fvSolution") + """
solvers
{
    p
    {
        solver          GAMG;
        tolerance       1e-7;
        relTol          0.01;
        smoother        GaussSeidel;
    }
    "(U|k|omega)"
    {
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-8;
        relTol          0.1;
    }
    pa
    {
        solver          GAMG;
        tolerance       1e-7;
        relTol          0.01;
        smoother        GaussSeidel;
    }
    "(Ua|ka|wa)"
    {
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-8;
        relTol          0.1;
    }
    // "ma" is solved during the point-based sensitivity's mesh-movement/
    // eikonal step (triggered by adjointEikonalSolver in optimisationDict),
    // not by the flow/adjoint-flow equations above -- verified against
    // sensitivityMaps/motorBike/system/fvSolution, the only shipped
    // surfacePoints-sensitivity example with an fvSolution entry for it.
    ma
    {
        solver           PCG;
        preconditioner   DIC;
        tolerance        1e-9;
        relTol           0.01;
    }
}

SIMPLE
{
    nNonOrthogonalCorrectors 1;
    residualControl
    {
        p               1e-4;
        U               1e-4;
        "(k|omega)"     1e-4;
    }
}

relaxationFactors
{
    equations
    {
        U               0.9;
        "(k|omega)"     0.7;
        // ADJOINT MOMENTUM IS RELAXED HARDER THAN THE PRIMAL. Was 0.9 -- the
        // same as the primal -- which is aggressive for an adjoint, and this
        // geometry is the worst case for it: a bluff rectangular block with
        // sharp edges in ground effect, separating off every corner.
        //
        // Evidence it is the adjoint MOMENTUM and not the turbulence model:
        // the SIGFPE landed in divDevReff -> fvmLaplacian(nuEff, Ua) with BOTH
        // adjointkOmegaSST and adjointLaminar, at adjoint iteration ~277 and
        // ~282 respectively -- i.e. model-independent and reproducible. Mesh
        // was clean both times (non-orthogonality 64.6, skewness 2.8, checkMesh
        // "Mesh OK"). And Uaz never converged: 1 -> 0.44 -> 0.10 -> 0.125, a
        // mode plateauing near 10% and oscillating until it overflows, while
        // Uax/Uay sat at ~0.002.
        //
        // 0.4 is a NUMERICAL stabilisation -- it changes nothing about the
        // objective or the physics, only how far each iteration steps. It is
        // deliberately tried before ATCModel `cancel`, which would stabilise by
        // DROPPING the adjoint transpose convection term (a real approximation
        // to the sensitivity). Exhaust numerics before approximating physics.
        // If this still diverges, `cancel` is the next lever.
        Ua              0.4;
        "(ka|wa)"       0.5;
    }
}
"""
