"""
openfoam_adjoint.py — drag-adjoint surface sensitivity for the half-car CFD
case, using ESI's `adjointOptimisationFoam`.

This is the piece that makes the OpenFOAM case actually "work with the 3
parts": Part 3's `pipeline_interface.real_bindings.run_adjoint` is a hard
`? UNRESOLVED NotImplementedError` stub (see part3-simulation/pipeline_interface.py),
and Part 1's `phi_updater.apply_adjoint_sensitivity_symmetric` (aka `update_phi`)
requires a `right_half_sensitivity` array with exactly one scalar per vertex of
the right-half trimesh, in the SAME order as `mesh.vertices`. This module
produces that array.

Turbulence pairing: kOmegaSST (primal) / adjointkOmegaSST (adjoint) — matching
the Part 2 spec's own stated turbulence model ("laminar baseline, k-omega SST
for final validation"), so the sensitivity field is computed with the SAME
closure used to validate D20/L/Cm, rather than mixing in an unrelated model.

An earlier version of this module used Spalart-Allmaras, on the mistaken
assumption (from having found only ONE tutorial) that it was the only
primal/adjoint turbulence pairing ESI ships. That was wrong: inspecting the
compiled libadjointOptimisation.so's symbol table shows `adjointkOmegaSST` is
a complete, independently-registered adjointRASModel implementation (same
factory table as adjointSpalartAllmaras) with its own tutorials
(shapeOptimisation/naca0012/kOmegaSST/lift and
shapeOptimisation/sbend/turbulent/kOmegaSST/opt, openfoam2412). Both were
used as the ground truth for the boundary conditions and dict schema below —
not assumed from documentation.

Design:
  * `optimisationManager singleRun` — ONE invocation of adjointOptimisationFoam
    runs the primal solve (SIMPLE, kOmegaSST, nIters primal_iters) and then the
    adjoint solve (adjointSimple, adjointkOmegaSST, nIters adjoint_iters)
    internally, driven entirely by optimisationDict. No separate solver
    binaries to call.
  * The primal U/p/k/omega/nut fields are generated by
    openfoam_case._write_initial_fields (same domain, same patches, same
    wall-function conventions already live-verified for the forward-only
    case) — not duplicated here.
  * The objective is `type force, direction (1,0,0)` (raw drag), weight 1 —
    i.e. the CFD side computes unweighted dD20/dSurface. The project's
    Objective = w_D20 x D20 x ADJOINT_HALF_CAR_SCALING (Part 2's
    adjoint_contract.py) is linear in this, so the business-logic weight and
    the 0.5 half-car scaling are applied in Python afterward, not baked into
    the OpenFOAM dict.
  * `sensitivityType surfacePoints` on the `car` patch gives a sensitivity
    value AT MESH POINTS directly (not per-face) — the right shape for a
    per-vertex array — but those points are snappyHexMesh's own (snapped)
    surface points, not the original STL's vertices. This module
    nearest-neighbour-maps snappy's sensitivity points back onto the ORIGINAL
    STL's vertex coordinates (via scipy.spatial.cKDTree) so the returned
    array lines up 1:1, in order, with `trimesh.load(stl_path).vertices` —
    exactly what Part 1 expects to zip against its own mesh.
"""

from __future__ import annotations

import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import numpy as np

import openfoam_case as oc


@dataclass(frozen=True)
class AdjointRunConfig:
    """Config for the drag-adjoint sensitivity solve.

    Turbulence is always kOmegaSST (primal) / adjointkOmegaSST (adjoint) —
    matching Part 2's forward validation model (see module docstring). There
    is no turbulence_model choice here, unlike OpenFOAMRunConfig.
    """

    reference_speed_mps: float = 20.0
    air_density_kgm3: float = 1.225
    kinematic_viscosity_m2s: float = oc._MU_AIR_PA_S / 1.225
    primal_iters: int = 1000
    adjoint_iters: int = 1000
    resolution: str = "medium"
    n_subdomains: int = 1
    keep_run_dir: bool = False
    # Nearest-neighbour matches beyond this distance (m) from any original STL
    # vertex are treated as unmapped and raise, rather than silently pairing
    # a sensitivity value with the wrong point.
    max_point_match_distance_m: float = 5e-3

    def __post_init__(self):
        if self.resolution not in oc.RESOLUTION_REFINEMENT:
            raise ValueError(
                f"resolution must be one of {sorted(oc.RESOLUTION_REFINEMENT)}, "
                f"got {self.resolution!r}"
            )
        if self.reference_speed_mps <= 0:
            raise ValueError("reference_speed_mps must be > 0")
        if self.primal_iters <= 0 or self.adjoint_iters <= 0:
            raise ValueError("primal_iters and adjoint_iters must be > 0")

    def as_forward_config(self) -> oc.OpenFOAMRunConfig:
        """Adapts this config to openfoam_case.OpenFOAMRunConfig so the
        primal U/p/k/omega/nut fields and turbulenceProperties can be
        generated by the same, already-verified functions the forward-only
        case uses — same domain, same patches, same wall functions."""
        return oc.OpenFOAMRunConfig(
            reference_speed_mps=self.reference_speed_mps,
            air_density_kgm3=self.air_density_kgm3,
            kinematic_viscosity_m2s=self.kinematic_viscosity_m2s,
            turbulence_model="kOmegaSST",
            resolution=self.resolution,
            n_subdomains=self.n_subdomains,
        )


# ---------------------------------------------------------------------------
# Dictionary builders (pure, unit-tested)
# ---------------------------------------------------------------------------

def build_adjoint_ras_properties() -> str:
    """Verified against tutorials/incompressible/adjointOptimisationFoam/
    shapeOptimisation/naca0012/kOmegaSST/lift/constant/adjointRASProperties —
    unlike the SA pairing, kOmegaSST needs no extra coeffs sub-dict here."""
    return oc._header("dictionary", "adjointTurbulenceProperties") + """
adjointRASModel adjointkOmegaSST;

adjointTurbulence on;
"""


def build_adjoint_control_dict(cfg: AdjointRunConfig) -> str:
    end_time = cfg.primal_iters + cfg.adjoint_iters
    write_interval = max(cfg.primal_iters, 1)
    return oc._header("dictionary", "controlDict") + f"""
application     adjointOptimisationFoam;
startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         {end_time};
deltaT          1;
writeControl    timeStep;
writeInterval   {write_interval};
purgeWrite      2;
writeFormat     ascii;
writePrecision  8;
writeCompression off;
timeFormat      general;
timePrecision   6;
runTimeModifiable true;
"""


def build_optimisation_dict(cfg: AdjointRunConfig, ref_area_half: float) -> str:
    """`singleRun` manager: one primal solve (kOmegaSST) then one adjoint
    solve (adjointkOmegaSST), objective = raw drag force (weight 1 — see
    module docstring for why the business weight is applied in Python, not
    here). residualControl includes k/omega (primal) and ka/wa (adjoint) —
    verified against sbend/turbulent/kOmegaSST/opt, which is the only shipped
    example with the k/omega transport equations actually solved (the
    naca0012 case's residual entries were not fully shown). sensitivityType
    is `surfacePoints` only (the reference tutorials also compute smoothed
    face-based variants for comparison; we only need the per-point one to
    match Part 1's per-vertex contract)."""
    aref = max(ref_area_half, 1e-9)
    u = cfg.reference_speed_mps
    rho = cfg.air_density_kgm3
    return oc._header("dictionary", "optimisationDict") + f"""
optimisationManager singleRun;

primalSolvers
{{
    op1
    {{
        active                 true;
        type                   incompressible;
        solver                 simple;

        solutionControls
        {{
            consistent yes;
            nIters {cfg.primal_iters};
            residualControl
            {{
                "p.*"       1.e-5;
                "U.*"       1.e-5;
                "k.*"       1.e-5;
                "omega.*"   1.e-5;
            }}
        }}
    }}
}}

adjointManagers
{{
    adjManager1
    {{
        primalSolver             op1;
        adjointSolvers
        {{
            adjS1
            {{
                active                 true;
                type                   incompressible;
                solver                 adjointSimple;

                objectives
                {{
                    type incompressible;
                    objectiveNames
                    {{
                        drag
                        {{
                            weight     1.;
                            type       force;
                            patches    (car);
                            direction  (1 0 0);
                            Aref       {aref};
                            rhoInf     {rho};
                            UInf       {u};
                        }}
                    }}
                }}

                ATCModel
                {{
                    ATCModel          standard;
                }}

                solutionControls
                {{
                    consistent yes;
                    nIters {cfg.adjoint_iters};
                    residualControl
                    {{
                        "pa.*"       1.e-5;
                        "Ua.*"       1.e-5;
                        "ka.*"       1.e-5;
                        "wa.*"       1.e-5;
                    }}
                }}
            }}
        }}
    }}
}}

optimisation
{{
    designVariables
    {{
        // Only the per-point sensitivity type is requested (the reference
        // tutorials also compute smoothed face-based variants for
        // comparison; we skip those -- Part 1's contract wants exactly one
        // scalar per surface vertex, which surfacePoints gives directly).
        sensitivityType    surfacePoints;
        patches            (car);
        adjointEikonalSolver
        {{
            tolerance 1.e-5;
            iters     1000;
            epsilon   0.1;
        }}
    }}
}}
"""


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _write_adjoint_fields(zero_dir: Path) -> None:
    """Ua/pa/ka/wa for MY 7-patch domain (inlet, outlet, symmetry, outer,
    upperWall, lowerWall, car). BC types verified against the shipped
    kOmegaSST adjoint tutorials:
      - wall types (kaqRWallFunction, waWallFunction, adjointWallVelocity):
        naca0012/kOmegaSST/lift and sbend/turbulent/kOmegaSST/opt.
      - inlet/outlet types for a domain with SEPARATE inlet and outlet
        patches (my domain, unlike naca0012's single combined freestream
        patch): sbend/turbulent/kOmegaSST/opt, the only shipped kOmegaSST
        example with distinct Inlet/Outlet patches.
      - pa's outlet type here is adjointFarFieldPressure (not sbend's
        adjointOutletPressure): my domain is an open external-aero far-field
        boundary (matches the topology of the SA motorBike case, which used
        adjointFarFieldPressure), not an enclosed duct exit like sbend.
      - outer/upperWall (slip, non-wall, non-farfield) have no confirmed
        reference for ka/wa; `slip` is used there for consistency with how
        Ua/p/k/omega already treat those patches as generic slip boundaries
        in this project's own (already-verified) forward case.
    """
    _write(zero_dir / "Ua", oc._header("volVectorField", "Ua") + """
dimensions      [0 1 -1 0 0 0 0];
internalField   uniform (0 0 0);
boundaryField
{
    inlet       { type adjointInletVelocity; value uniform (0 0 0); }
    outlet      { type adjointOutletVelocity; value uniform (0 0 0); }
    symmetry    { type symmetryPlane; }
    outer       { type slip; }
    upperWall   { type slip; }
    lowerWall   { type adjointWallVelocity; value uniform (0 0 0); }
    car         { type adjointWallVelocity; value uniform (0 0 0); }
}
""")
    _write(zero_dir / "pa", oc._header("volScalarField", "pa") + """
dimensions      [0 2 -2 0 0 0 0];
internalField   uniform 0;
boundaryField
{
    inlet       { type zeroGradient; }
    outlet      { type adjointFarFieldPressure; value uniform 0; }
    symmetry    { type symmetryPlane; }
    outer       { type zeroGradient; }
    upperWall   { type zeroGradient; }
    lowerWall   { type zeroGradient; }
    car         { type zeroGradient; }
}
""")
    _write(zero_dir / "ka", oc._header("volScalarField", "ka") + """
dimensions      [0 0 0 0 0 0 0];
internalField   uniform 0;
boundaryField
{
    inlet       { type adjointZeroInlet; value uniform 0; }
    outlet      { type adjointOutletKa; value uniform 0; }
    symmetry    { type symmetryPlane; }
    outer       { type slip; }
    upperWall   { type slip; }
    lowerWall   { type kaqRWallFunction; value uniform 0; }
    car         { type kaqRWallFunction; value uniform 0; }
}
""")
    _write(zero_dir / "wa", oc._header("volScalarField", "wa") + """
dimensions      [0 2 -1 0 0 0 0];
internalField   uniform 0;
boundaryField
{
    inlet       { type adjointZeroInlet; value uniform 0; }
    outlet      { type adjointOutletWa; value uniform 0; }
    symmetry    { type symmetryPlane; }
    outer       { type slip; }
    upperWall   { type slip; }
    lowerWall   { type waWallFunction; value uniform 0; }
    car         { type waWallFunction; value uniform 0; }
}
""")


# ---------------------------------------------------------------------------
# Case assembly + orchestration
# ---------------------------------------------------------------------------

def build_adjoint_case(run_dir: str, stl_path: str, cfg: AdjointRunConfig) -> dict:
    """Generate a complete adjoint case under run_dir. Reuses the geometry
    (bounds, domain box, blockMesh/snappy/surfaceFeatureExtract/meshQuality
    dict builders, and the primal U/p/k/omega/nut/turbulenceProperties
    writers) from openfoam_case.py — only adjointRASProperties, the adjoint
    0/ fields, optimisationDict, and controlDict's application differ from
    the forward-only case."""
    run = Path(run_dir)
    if run.exists():
        shutil.rmtree(run)
    (run / "system").mkdir(parents=True, exist_ok=True)
    (run / "constant" / "triSurface").mkdir(parents=True, exist_ok=True)
    (run / "0").mkdir(parents=True, exist_ok=True)

    forward_cfg = cfg.as_forward_config()

    bounds = oc.stl_bounds(stl_path)
    (x0, y0, z0), (x1, y1, z1) = bounds
    ref_len = max(x1 - x0, 1e-4)
    frontal_area_half = oc.compute_frontal_area_half(stl_path)
    box_min, box_max = oc.domain_box(bounds)
    loc = oc.location_in_mesh(bounds)
    cell_size = max(ref_len / 12.0, 1e-4)

    oc._normalise_solid_name(stl_path, run / "constant" / "triSurface" / "car.stl")

    refinement = oc.RESOLUTION_REFINEMENT[cfg.resolution]

    _write(run / "system" / "blockMeshDict", oc.build_blockmesh_dict(box_min, box_max, cell_size))
    _write(run / "system" / "snappyHexMeshDict",
           oc.build_snappy_dict("car.stl", loc, refinement, add_layers=True))
    _write(run / "system" / "controlDict", build_adjoint_control_dict(cfg))
    _write(run / "system" / "fvSchemes", _FV_SCHEMES_ADJOINT)
    _write(run / "system" / "fvSolution", _FV_SOLUTION_ADJOINT)
    _write(run / "system" / "surfaceFeatureExtractDict",
           oc._header("dictionary", "surfaceFeatureExtractDict") + oc._SURFACE_FEATURE_EXTRACT_BODY)
    _write(run / "system" / "meshQualityDict", oc._MESH_QUALITY_DICT)
    _write(run / "system" / "decomposeParDict", oc._decompose_dict(cfg.n_subdomains))
    _write(run / "system" / "optimisationDict", build_optimisation_dict(cfg, frontal_area_half))
    _write(run / "constant" / "transportProperties", oc.build_transport_properties(forward_cfg))
    _write(run / "constant" / "turbulenceProperties", oc.build_turbulence_properties(forward_cfg))
    _write(run / "constant" / "adjointRASProperties", build_adjoint_ras_properties())

    # Primal fields (U, p, k, omega, nut) -- same domain/patches/wall
    # functions as the already-verified forward-only case.
    oc._write_initial_fields(run / "0", forward_cfg, ref_len)
    # Adjoint fields (Ua, pa, ka, wa).
    _write_adjoint_fields(run / "0")

    return {
        "bounds": bounds,
        "frontal_area_half": frontal_area_half,
        "cell_size_m": cell_size,
        "domain_box": (box_min, box_max),
        "location_in_mesh": loc,
    }


def run_adjoint_stages(run_dir: str, cfg: AdjointRunConfig, bashrc: str, timeout_s: int = 14400) -> dict:
    """surfaceFeatureExtract -> blockMesh -> snappyHexMesh -> checkMesh ->
    adjointOptimisationFoam (single invocation runs primal then adjoint,
    per optimisationDict's singleRun manager)."""
    run = Path(run_dir)
    oc._run("surfaceFeatureExtract", run, bashrc, "surfaceFeatureExtract.log", timeout_s)
    oc._run("blockMesh", run, bashrc, "blockMesh.log", timeout_s)
    if cfg.n_subdomains > 1:
        oc._run("decomposePar -force", run, bashrc, "decomposePar.log", timeout_s)
        oc._run(f"mpirun -np {cfg.n_subdomains} snappyHexMesh -overwrite -parallel",
                run, bashrc, "snappyHexMesh.log", timeout_s)
        checkmesh = oc._run(f"mpirun -np {cfg.n_subdomains} checkMesh -parallel",
                            run, bashrc, "checkMesh.log", timeout_s)
        solver_log = oc._run(f"mpirun -np {cfg.n_subdomains} adjointOptimisationFoam -parallel",
                             run, bashrc, "adjoint.log", timeout_s)
        oc._run("reconstructPar -latestTime", run, bashrc, "reconstructPar.log", timeout_s)
    else:
        oc._run("snappyHexMesh -overwrite", run, bashrc, "snappyHexMesh.log", timeout_s)
        checkmesh = oc._run("checkMesh", run, bashrc, "checkMesh.log", timeout_s)
        solver_log = oc._run("adjointOptimisationFoam", run, bashrc, "adjoint.log", timeout_s)
    return {"checkmesh_log": checkmesh, "solver_log": solver_log}


# ---------------------------------------------------------------------------
# Sensitivity output discovery + parsing (pure, unit-tested against fixtures)
# ---------------------------------------------------------------------------

def find_sensitivity_file(run_dir: str) -> Path:
    """Locate the surfacePoints sensitivity output.

    Verified against a live run (openfoam2412): the file is named
    `pointSensNormal<adjointSolverName><suffix>` (here `pointSensNormaladjS1ESI`,
    from optimisationDict's adjoint solver name `adjS1`) and is written as a
    plain `pointScalarField` covering EVERY point of the volume mesh (not a
    curated list of just the design-patch points) — most values are 0, with
    nonzero values at points on/near the sensitivity patch. This is a
    different shape than the naive assumption of a small "list of (point,
    value) pairs on the patch" file; that assumption was wrong and this was
    only discovered by actually running the solver and inspecting its output
    directory, not from documentation.

    We search for `pointSensNormal*` broadly rather than hardcoding the exact
    solver-name suffix, and take the newest match (highest write time), so a
    different adjoint solver name in optimisationDict still resolves.
    """
    root = Path(run_dir)
    candidates = [p for p in root.rglob("pointSensNormal*") if p.is_file()]
    if not candidates:
        raise FileNotFoundError(
            f"No pointSensNormal* sensitivity output found under {run_dir}. "
            "Expected a pointScalarField file written by the surfacePoints "
            "sensitivity type, named pointSensNormal<adjointSolverName><suffix>."
        )
    return max(candidates, key=lambda p: p.stat().st_mtime)


def _parse_foam_scalar_list(text: str) -> np.ndarray:
    """Parse the `internalField nonuniform List<scalar> N ( v1 v2 ... vN )`
    block of an OpenFOAM pointScalarField/volScalarField ASCII file.

    Scans for a bare integer count line immediately followed by a `(` line
    (the "N\\n(\\n...\\n)" list convention OpenFOAM uses everywhere), rather
    than a single regex over the whole file, so a boundaryField sub-dict
    elsewhere in the same file can't confuse the match.
    """
    lines = text.splitlines()
    start = None
    count = None
    for i, line in enumerate(lines):
        s = line.strip()
        if s.isdigit() and i + 1 < len(lines) and lines[i + 1].strip() == "(":
            start = i + 2
            count = int(s)
            break
    if start is None or count is None:
        raise ValueError("Could not find a 'N\\n(\\n...values...\\n)' list in the field file")
    values = []
    for line in lines[start:]:
        s = line.strip()
        if s == ")":
            break
        if not s:
            continue
        try:
            values.append(float(s))
        except ValueError:
            continue
    if len(values) != count:
        raise ValueError(f"Expected {count} scalar values, parsed {len(values)}")
    return np.array(values, dtype=np.float64)


def _parse_foam_vector_list(text: str) -> np.ndarray:
    """Parse a `N\\n(\\n(x y z)\\n...\\n)` OpenFOAM vectorField/pointField
    (used for constant/polyMesh/points)."""
    lines = text.splitlines()
    start = None
    count = None
    for i, line in enumerate(lines):
        s = line.strip()
        if s.isdigit() and i + 1 < len(lines) and lines[i + 1].strip() == "(":
            start = i + 2
            count = int(s)
            break
    if start is None or count is None:
        raise ValueError("Could not find a 'N\\n(\\n(x y z)...\\n)' list in the points file")
    rows = []
    for line in lines[start:]:
        s = line.strip()
        if s == ")":
            break
        if not s:
            continue
        m = re.match(r"\(\s*([0-9.eE+-]+)\s+([0-9.eE+-]+)\s+([0-9.eE+-]+)\s*\)", s)
        if m:
            rows.append([float(m.group(1)), float(m.group(2)), float(m.group(3))])
    if len(rows) != count:
        raise ValueError(f"Expected {count} points, parsed {len(rows)}")
    return np.array(rows, dtype=np.float64)


def read_polymesh_points(run_dir: str) -> np.ndarray:
    """Read constant/polyMesh/points -> array of shape (N, 3), index-aligned
    with the sensitivity pointScalarField's internalField (both are per
    mesh-point, same N, same order — this is how OpenFOAM point fields work:
    they're defined directly over the mesh's point list)."""
    path = Path(run_dir) / "constant" / "polyMesh" / "points"
    if not path.is_file():
        raise FileNotFoundError(f"constant/polyMesh/points not found under {run_dir}")
    return _parse_foam_vector_list(path.read_text(encoding="utf-8", errors="replace"))


def parse_sensitivity_points(sensitivity_text: str, points: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Pair the sensitivity pointScalarField's values with mesh point
    coordinates (both index-aligned by mesh point ID). Returns (points[N,3],
    values[N]) covering every mesh point -- including the many zero-valued
    interior points, which is fine: map_sensitivity_to_stl_vertices's nearest-
    neighbour search will naturally prefer the nearby nonzero surface points
    over distant interior ones, and the max-distance guard catches anything
    that goes wrong."""
    values = _parse_foam_scalar_list(sensitivity_text)
    if len(values) != len(points):
        raise ValueError(
            f"Sensitivity field has {len(values)} values but the mesh has "
            f"{len(points)} points -- they must be the same mesh."
        )
    return points, values


def map_sensitivity_to_stl_vertices(
    stl_path: str,
    sens_points: np.ndarray,
    sens_values: np.ndarray,
    max_distance_m: float,
) -> np.ndarray:
    """Nearest-neighbour-map CFD-mesh sensitivity points onto the ORIGINAL
    STL's vertex order, so the result lines up 1:1 with
    `trimesh.load(stl_path).vertices` — the shape Part 1's
    apply_adjoint_sensitivity_symmetric (right_half_sensitivity) requires.

    snappyHexMesh snaps surface points to the geometry within a small
    tolerance, so CFD points are close to but not identical to STL vertices;
    nearest-neighbour is the correct correspondence here, not an exact match.
    Raises if any STL vertex has no CFD sensitivity point within
    max_distance_m — silently assigning a distant, wrong value would corrupt
    the phi update rather than fail loudly.
    """
    from scipy.spatial import cKDTree

    stl_verts = np.array(oc.read_ascii_stl_vertices(stl_path), dtype=np.float64)
    tree = cKDTree(sens_points)
    dist, idx = tree.query(stl_verts, k=1)
    bad = dist > max_distance_m
    if np.any(bad):
        n_bad = int(np.sum(bad))
        raise ValueError(
            f"{n_bad}/{len(stl_verts)} STL vertices have no adjoint sensitivity "
            f"point within {max_distance_m} m. The adjoint mesh may not cover "
            "the full surface, or geometry drifted between the STL and the "
            "meshed case."
        )
    return sens_values[idx]


# ---------------------------------------------------------------------------
# Top-level entry point
# ---------------------------------------------------------------------------

def invoke_adjoint(
    stl_path: str,
    case_dir: str,
    cfg: Optional[AdjointRunConfig] = None,
    bashrc: Optional[str] = None,
) -> np.ndarray:
    """Full adjoint pipeline: build case, run primal+adjoint, parse
    sensitivity, map onto the original STL's vertex order.

    Returns the RAW (unweighted, weight=1 drag-direction) per-vertex
    dD20_half/dSurface sensitivity array. Applying the project's objective
    weight (w_D20) and ADJOINT_HALF_CAR_SCALING is the caller's job
    (cfd_wrapper.run_half_car_adjoint) — see module docstring for why.
    """
    import os

    cfg = cfg or AdjointRunConfig()
    resolved_bashrc = oc.find_openfoam_bashrc(bashrc)
    if resolved_bashrc is None:
        raise oc.OpenFOAMNotFoundError(
            "No ESI OpenFOAM environment found for the adjoint solve. Set "
            "$WM_PROJECT_DIR or $FOAM_BASHRC, or pass bashrc=... ."
        )
    run_dir = str(Path(case_dir) / "adjoint_runs" / f"run_{os.getpid()}_{abs(hash(stl_path)) % 10_000}")
    build_adjoint_case(run_dir, stl_path, cfg)
    try:
        run_adjoint_stages(run_dir, cfg, resolved_bashrc)
        sens_file = find_sensitivity_file(run_dir)
        mesh_points = read_polymesh_points(run_dir)
        sens_points, sens_values = parse_sensitivity_points(
            sens_file.read_text(encoding="utf-8", errors="replace"), mesh_points
        )
        return map_sensitivity_to_stl_vertices(
            stl_path, sens_points, sens_values, cfg.max_point_match_distance_m
        )
    finally:
        if not cfg.keep_run_dir:
            shutil.rmtree(run_dir, ignore_errors=True)


_FV_SCHEMES_ADJOINT = oc._header("dictionary", "fvSchemes") + """
ddtSchemes
{
    default         steadyState;
}

gradSchemes
{
    default         Gauss linear;
}

divSchemes
{
    default            Gauss linear;

    div(phi,U)         bounded Gauss linearUpwind gradUConv;
    div(phi,k)         bounded Gauss linearUpwind gradKConv;
    div(phi,omega)     bounded Gauss linearUpwind gradOmegaConv;
    div(-phi,Ua)       bounded Gauss linearUpwind gradUaConv;
    div(-phi,ka)       bounded Gauss linearUpwind gradKaConv;
    div(-phi,wa)       bounded Gauss linearUpwind gradWaConv;
}

laplacianSchemes
{
    default         Gauss linear limited 0.333;
}

interpolationSchemes
{
    default         linear;
}

snGradSchemes
{
    default         limited 0.333;
}

wallDist
{
    method meshWave;
}
"""

_FV_SOLUTION_ADJOINT = oc._header("dictionary", "fvSolution") + """
solvers
{
    p
    {
        solver          GAMG;
        tolerance       1e-7;
        relTol          0.01;
        smoother        GaussSeidel;
    }
    "(U|k|omega)"
    {
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-8;
        relTol          0.1;
    }
    pa
    {
        solver          GAMG;
        tolerance       1e-7;
        relTol          0.01;
        smoother        GaussSeidel;
    }
    "(Ua|ka|wa)"
    {
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-8;
        relTol          0.1;
    }
    // "ma" is solved during the point-based sensitivity's mesh-movement/
    // eikonal step (triggered by adjointEikonalSolver in optimisationDict),
    // not by the flow/adjoint-flow equations above -- verified against
    // sensitivityMaps/motorBike/system/fvSolution, the only shipped
    // surfacePoints-sensitivity example with an fvSolution entry for it.
    ma
    {
        solver           PCG;
        preconditioner   DIC;
        tolerance        1e-9;
        relTol           0.01;
    }
}

SIMPLE
{
    nNonOrthogonalCorrectors 1;
    residualControl
    {
        p               1e-4;
        U               1e-4;
        "(k|omega)"     1e-4;
    }
}

relaxationFactors
{
    equations
    {
        U               0.9;
        "(k|omega)"     0.7;
        Ua              0.9;
        "(ka|wa)"       0.7;
    }
}
"""
